# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BRANDNAMEID', models.BigIntegerField(null=True)),
                ('BRANDNAME', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATEGORYID', models.BigIntegerField(null=True)),
                ('CATEGORYNAME', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.BigIntegerField(null=True)),
                ('PRODUCTNAME', models.CharField(max_length=100)),
                ('SMURL', models.CharField(max_length=200)),
                ('COVERURL', models.CharField(max_length=2000)),
                ('PRICE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DETAILS', models.TextField()),
                ('BRANDNAMEID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Item.Brand')),
                ('CATEGORYID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Item.Category')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='CATEGORYID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Item.Category'),
        ),
    ]
