# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0002_remove_item_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='CATEGORYID',
        ),
        migrations.AlterField(
            model_name='item',
            name='BRANDNAMEID',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='CATEGORYID',
            field=models.BigIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
