# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 18:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Item', '0005_auto_20160611_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Item', to=settings.AUTH_USER_MODEL),
        ),
    ]
